spring:
  messages:
    basename: messages
    encoding: UTF-8
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
key:
  jwt-secret: JWTSecretKey
  jwt-expiration: 604800001
server:
  error:
    include-message: always
    include-binding-errors: always  
 
  
 
    
